"""Report generation utilities."""

import json
from datetime import datetime
from typing import Any


class ReportGenerator:
    """Generate analysis reports."""

    def generate_html_report(self, title: str, sections: list[dict[str, Any]]) -> str:
        """Generate an HTML report from sections."""
        section_html = ""
        for section in sections:
            section_html += f"""
<div class="section">
    <h2>{section.get('title', 'Section')}</h2>
    <div class="content">{section.get('content', '')}</div>
</div>
"""
        return f"""<!DOCTYPE html>
<html>
<head>
    <title>{title}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }}
        h2 {{ color: #2980b9; }}
        .section {{ margin: 20px 0; padding: 15px; background: #f8f9fa; border-radius: 8px; }}
        .meta {{ color: #7f8c8d; font-size: 0.9em; }}
        table {{ border-collapse: collapse; width: 100%; }}
        th, td {{ border: 1px solid #ddd; padding: 8px; text-align: left; }}
        th {{ background: #3498db; color: white; }}
        tr:nth-child(even) {{ background: #f2f2f2; }}
    </style>
</head>
<body>
    <h1>{title}</h1>
    <p class="meta">Generated by BioInfo Agent on {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
    {section_html}
</body>
</html>"""

    def format_de_results(self, results) -> str:
        """Format DE results as an HTML table."""
        if hasattr(results, "head"):
            top = results.head(20)
            rows = ""
            for _, row in top.iterrows():
                rows += f"""<tr>
                    <td>{row.get('gene', '')}</td>
                    <td>{row.get('baseMean', 0):.1f}</td>
                    <td>{row.get('log2FoldChange', 0):.3f}</td>
                    <td>{row.get('pvalue', 0):.2e}</td>
                    <td>{row.get('padj', 0):.2e}</td>
                    <td>{row.get('regulation', '')}</td>
                </tr>"""
            return f"""<table>
                <tr><th>Gene</th><th>Base Mean</th><th>log2FC</th><th>P-value</th><th>Adj P-value</th><th>Regulation</th></tr>
                {rows}
            </table>"""
        return "<p>No results to display</p>"

    def format_enrichment_results(self, results) -> str:
        """Format enrichment results as an HTML table."""
        if hasattr(results, "head"):
            top = results.head(15)
            rows = ""
            for _, row in top.iterrows():
                rows += f"""<tr>
                    <td>{row.get('term_name', '')}</td>
                    <td>{row.get('term_id', '')}</td>
                    <td>{row.get('overlap', 0)}/{row.get('term_size', 0)}</td>
                    <td>{row.get('enrichment_factor', 0):.2f}x</td>
                    <td>{row.get('padj', 0):.2e}</td>
                </tr>"""
            return f"""<table>
                <tr><th>Term</th><th>ID</th><th>Overlap</th><th>Enrichment</th><th>Adj P-value</th></tr>
                {rows}
            </table>"""
        return "<p>No enrichment results</p>"
